name: Auto filling pull request
on:
  pull_request:
    types: [opened]

jobs:
  auto-filling-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set assignee
        uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Add labels based on PR title
        uses: TDAK1509/set-label-based-on-pr-title@master
        with:
          words: WIP;UnitTest;E2E
          labels: PR:draft;PR:unittest;PR:e2e
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
