name: Auto filling pull request
on:
  pull_request:

jobs:
  auto-filling-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Set assignee
        uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
